### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by Pardaramskha** [Pardaramskha/lets-a-go#1]
- [x] learn basic Go syntax
- [x] lean basic Go api architecture
- [x] learn how to docker a postgresDB
- [x] learn basic SQL commands
- [ ] learn better things about DataGrip
- [ ] lean better things about Docker (basic commands for running containers)
- [ ] learn how to dockerise something
- [ ] learn better Go architecture
- [x] learn CORS with Go
